Add a "test gate" before tag_and_release

diff --git a/.github/workflows/release-plugin.yml b/.github/workflows/release-plugin.yml
--- a/.github/workflows/release-plugin.yml
+++ b/.github/workflows/release-plugin.yml
@@ -97,9 +97,28 @@ jobs:
     if: github.event.inputs.skip_tests == false
     uses: ./.github/workflows/e2e-tests.yml
 
+  check_tests:
+    needs: [ validate_version, integration_tests, e2e_tests ]
+    runs-on: ubuntu-latest
+    if: needs.validate_version.result == 'success' && (github.event.inputs.skip_tests || (needs.integration_tests.result == 'success' && needs.e2e_tests.result == 'success'))
+    steps:
+      - name: Checks if tests passed or were skipped
+        run: |
+          if [[ "${{ github.event.inputs.skip_tests }}" == "true" ]]; then
+              echo "Tests were skipped."
+              return 0
+          fi
+
+          if [[ "${{ needs.integration_tests.result }}" == "success" && "${{ needs.e2e_tests.result }}" == "success" ]]; then
+              echo "All tests passed."
+              return 0
+          fi
+
+          echo "Tests failed."
+          exit 1
+
   tag_and_release:
-    needs: [validate_version, integration_tests, e2e_tests]
-    if: needs.validate_version.result == 'success' && ( github.event.inputs.skip_tests || ( needs.integration_tests.result == 'success' && needs.e2e_tests.result == 'success' ) )
+    needs: [check_tests]
     runs-on: ubuntu-latest
     outputs:
       tag_name: ${{ steps.tag.outputs.tag_name }}
